image: docker:latest

stages:
  - prepare
  - compile

prepare:
  stage: prepare
  services:
   - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -f Dockerfile1 -t registry.gitlab.com/insightpt/tensorflow/tf_build_env:latest .
    - docker push registry.gitlab.com/insightpt/tensorflow/tf_build_env:latest

compile:
  stage: compile
  image: registry.gitlab.com/insightpt/tensorflow/tf_build_env:latest
  script:
    - bash ./configure
    - bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
    - bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tensorflow_pkg
  artifacts:
    paths:
    - tensorflow_pkg/
    
